name: NuGet Generation

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1
          
      - name: Build solution and generate NuGet package
        run: |  
          cd src/Services
          dotnet workload restore
          dotnet pack -c Release -o out  

      - name: Push generated package to Nuget registry
        run: dotnet nuget push ./src/Services/out/*.nupkg --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json
