name: NuGet Generation

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
      
      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources
        
      - name: Build solution and generate NuGet package and Push
        run: |
          cd src/Services
          dotnet pack -c Release -o out
          cd out
          dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json