name: NuGet Generation

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x
          
      - name: Build solution and generate NuGet package and Push
        run: |
          cd src/Services
          sed -i "s/\(<VersionPrefix>\([0-9]\+\.\)\{2\}\)\([0-9]\+\)/\1${{github.run_number}}/" Turbo.Maui.Services.csproj
          dotnet workload restore
          dotnet pack -c Release -o out
          cd out
          dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json